using OpsDesk.Core.Enums;

namespace OpsDesk.Core.Entities;

/// <summary>
/// The central business entity — represents one customer support request.
///
/// Key design decisions:
/// - TicketCode is a human-readable identifier (TKT-2026-000001) generated on creation.
/// - DueAt is calculated once on creation from Priority SLA; it is immutable afterwards.
/// - RowVersion enables EF Core optimistic concurrency (see Phase 15).
/// - AssignedToUserId is nullable — New tickets have no assignee.
/// - We track ResolvedAt and ClosedAt as separate timestamps for audit/reporting.
/// - Hard delete is avoided; tickets are a historical record.
/// </summary>
public class Ticket
{
    public int Id { get; set; }

    /// <summary>
    /// Human-readable code, e.g. TKT-2026-000123.
    /// Generated by TicketService on creation and never changed.
    /// </summary>
    public string TicketCode { get; set; } = string.Empty;

    public int CustomerId { get; set; }
    public Customer Customer { get; set; } = null!;

    public string Subject { get; set; } = string.Empty;

    public string Description { get; set; } = string.Empty;

    public TicketPriority Priority { get; set; }

    public TicketStatus Status { get; set; } = TicketStatus.New;

    /// <summary>Nullable — no assignee when ticket is New.</summary>
    public string? AssignedToUserId { get; set; }
    public ApplicationUser? AssignedTo { get; set; }

    public string CreatedByUserId { get; set; } = string.Empty;
    public ApplicationUser CreatedBy { get; set; } = null!;

    /// <summary>
    /// SLA deadline. Calculated from CreatedAt + SLA hours based on Priority.
    /// Set once and never changed (even if Priority changes — a design choice to
    /// preserve the original commitment).
    /// </summary>
    public DateTime DueAt { get; set; }

    /// <summary>Set when status transitions to Resolved.</summary>
    public DateTime? ResolvedAt { get; set; }

    /// <summary>Set when status transitions to Closed. Cleared on Reopen.</summary>
    public DateTime? ClosedAt { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// EF Core optimistic concurrency token.
    /// SQL Server automatically increments this on every UPDATE.
    /// EF Core includes it in UPDATE WHERE clauses to detect concurrent edits.
    /// </summary>
    public byte[] RowVersion { get; set; } = [];

    // Navigation
    public ICollection<TicketMessage> Messages { get; set; } = [];
    public ICollection<TicketStatusHistory> StatusHistory { get; set; } = [];
    public ICollection<TicketAssignmentHistory> AssignmentHistory { get; set; } = [];
}
